// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/hermes/runs': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hermes/runs').default>>>>
    }
    '/api/hermes/runs/:id/approval': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hermes/runs/[id]/approval.post').default>>>>
    }
    '/api/hermes/runs/:id/events': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hermes/runs/[id]/events.get').default>>>>
    }
    '/api/hermes/runs/:id/stop': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hermes/runs/[id]/stop.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}