// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/19/2026, 9:12:00 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/opt/apps/hermes-webui/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/opt/apps/hermes-webui/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/opt/apps/hermes-webui/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/opt/apps/hermes-webui/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/opt/apps/hermes-webui/plugins/**/*.{js,ts,mjs}","/opt/apps/hermes-webui/composables/**/*.{js,ts,mjs}","/opt/apps/hermes-webui/utils/**/*.{js,ts,mjs}","/opt/apps/hermes-webui/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/opt/apps/hermes-webui/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/opt/apps/hermes-webui/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/opt/apps/hermes-webui/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;