<script setup lang="ts">
import type { MessageEntry } from '~/types/hermes'
import { downloadFile } from '~/utils/file-download'

const props = defineProps<{
  entry: MessageEntry
}>()

// Local collapsed state that users can toggle to expand
const isCollapsed = ref(props.entry.collapsed === true)

function toggleCollapsed() {
  isCollapsed.value = !isCollapsed.value
}

// Get first line of content for collapsed preview
const firstLine = computed(() => {
  const content = props.entry.content || ''
  const newlineIdx = content.indexOf('\n')
  return newlineIdx >= 0 ? content.slice(0, newlineIdx) : content
})

const hasMoreContent = computed(() => {
  const content = props.entry.content || ''
  return content.includes('\n') || content.length > 80
})
</script>

<template>
  <!-- Collapsed view: single-line compact bubble -->
  <div
    v-if="isCollapsed"
    class="flex mb-0.5 cursor-pointer group"
    :class="entry.role === 'user' ? 'justify-end' : 'justify-start'"
    @click="toggleCollapsed"
  >
    <div
      :class="[
        'max-w-[70%] rounded-xl px-3 py-1 text-xs leading-relaxed border transition-colors',
        entry.role === 'user'
          ? 'bg-blue-600/40 text-blue-200 border-blue-500/30 rounded-br-md hover:bg-blue-600/60'
          : 'bg-gray-800/50 text-gray-400 border-gray-700/40 rounded-bl-md hover:bg-gray-700/60',
      ]"
    >
      <span class="inline-block mr-1 opacity-50">▸</span>
      <span class="truncate inline-block max-w-[calc(100%-3rem)] align-bottom">
        {{ firstLine }}
      </span>
      <span v-if="hasMoreContent" class="text-gray-500 ml-1">…</span>
      <span class="ml-1.5 text-gray-500 group-hover:text-gray-300 transition-colors text-[10px]">展开</span>
    </div>
  </div>

  <!-- Expanded view: full message -->
  <div
    v-else
    class="flex mb-1"
    :class="entry.role === 'user' ? 'justify-end' : 'justify-start'"
  >
    <div
      :class="[
        'max-w-[80%] rounded-2xl px-4 py-2.5 text-sm leading-relaxed',
        entry.role === 'user'
          ? 'bg-blue-600 text-white rounded-br-md'
          : 'bg-gray-800 text-gray-100 rounded-bl-md',
      ]"
    >
      <template v-if="entry.role === 'assistant'">
        <MarkdownContent :content="entry.content" />
        <span
          v-if="entry.isStreaming"
          class="inline-block w-1.5 h-4 ml-0.5 bg-gray-400 animate-pulse rounded-sm align-text-bottom"
        />
      </template>
      <template v-else>
        <p class="whitespace-pre-wrap">{{ entry.content }}</p>
      </template>

      <!-- File attachments in user messages -->
      <div
        v-if="entry.role === 'user' && entry.attachments && entry.attachments.length > 0"
        class="flex flex-wrap gap-1 mt-2 pt-2 border-t border-white/20"
      >
        <FileAttachment
          v-for="file in entry.attachments"
          :key="file.file_id"
          :file="file"
          :removable="false"
          @download="downloadFile"
        />
      </div>

      <!-- Files generated by LLM tools -->
      <div
        v-if="entry.role === 'assistant' && entry.artifacts && entry.artifacts.length > 0"
        class="flex flex-wrap gap-1 mt-2 pt-2 border-t border-white/10"
      >
        <FileAttachment
          v-for="artifact in entry.artifacts"
          :key="artifact.file_id || artifact.artifact_id || artifact.id"
          :file="artifact"
          :removable="false"
          @download="downloadFile"
        />
      </div>

      <!-- Collapse button for expanded messages that were originally collapsed -->
      <div
        v-if="entry.collapsed"
        class="mt-1.5 pt-1.5 border-t border-white/10 text-center"
      >
        <button
          class="text-xs text-gray-500 hover:text-gray-300 transition-colors cursor-pointer"
          @click="toggleCollapsed"
        >
          收起 ▲
        </button>
      </div>
    </div>
  </div>
</template>
